alphabet_size: 4
args: !!python/object:argparse.Namespace
  accumulate_grad: 1
  alpha_max: 8
  alpha_scale: 2
  analytic_cls_score: false
  ardm_mask_prob_power: 1
  batch_size: 128
  burn_in: false
  check_grad: false
  check_val_every_n_epoch: 5
  checkpoint_layers: false
  ckpt: null
  ckpt_iterations: null
  clean_data: true
  cls_ckpt: null
  cls_expanded_simplex: false
  cls_free_guidance: false
  cls_guidance: false
  cls_model: cnn
  commit: 90882b392add689d0b51640a064b3b52e696f700
  constant_val_len: null
  crop_length: 1024
  data_dir: /data/anonymized/anonymized/uniref50
  dataset_type: enhancer
  dropout: 0.2
  fix_alpha: null
  fix_mask_prob: null
  flow_mode: dirichlet
  flow_temp: 1.0
  grad_clip: 1.0
  guidance_scale: 0.5
  hidden_dim: 128
  limit_train_batches: null
  limit_val_batches: null
  lr: 0.001
  lr_multiplier: 1.0
  max_steps: 450000
  mel_enhancer: true
  mode: dirichlet
  model: 650M
  no_lr_scheduler: false
  no_token_dropout: false
  no_tqdm: false
  no_weight_decay: false
  num_cnn_stacks: 4
  num_esmppl_batches: 0
  num_inf_batches: null
  num_integration_steps: 100
  num_layers: 1
  num_workers: 4
  overfit: false
  pepmlm_settings: false
  print_freq: 200
  prior_pseudocount: 2
  prior_self_condition: false
  promoter_dataset: false
  reinitialize: false
  remask_ardm: false
  restore_weights_only: false
  run_name: clsMELclean_cnn_dropout02
  scale_cls_score: false
  self_condition_ratio: 0
  simplex_encoding: none
  simplex_encoding_dim: 64
  simplex_spacing: 1000
  time_embed: false
  timewarp: false
  toy_num_cls: 3
  toy_num_seq: 1000
  toy_seq_len: 20
  toy_simplex_dim: 4
  txtfile_dataset: false
  val_check_interval: null
  val_pred_type: argmax
  validate: false
  validate_on_test: false
  validate_on_train: false
  wandb: true
num_cls: 47
